// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle/pkg/app"
	"github.com/go-microservice/moment-service/internal/server"
	"github.com/go-microservice/moment-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig) (*app.App, error) {
	greeterService := service.NewGreeterService()
	grpcServer := server.NewGRPCServer(config, greeterService)
	appApp := newApp(cfg, grpcServer)
	return appApp, nil
}
